development:
  adapter: postgresql
  encoding: unicode
  database: demo_app_development
  host: localhost
  port: 5433
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: demo_app_development
  host: localhost
  port: 5433
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: demo_app_development
  host: localhost
  port: 5433
  pool: 5
  username: postgres
  password: postgres
